version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME = localhost
      - DATABASE_PORT = 5432
      - DATABASE_PASSWORD = passward_that_you_set
      - DATABASE_NAME = name_of_database
      - DATABASE_USERNAME = User_name
      - SECRET_KEY = 09d25e094faa2556c818166b7a99f6f0f4c3b88e8d3e7 
      - ALGORITHM = HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES = 60
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=healthconnect-api
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
